"""Pure scaffold logic for `kitefs init` and `kitefs init-config`.

No printing, no Click. Returns summary strings; the caller does all I/O.
Top-level imports are exactly: pathlib, os, tempfile, json, kitefs.errors.
"""

from __future__ import annotations

import contextlib
import json
import os
import tempfile
from pathlib import Path

from kitefs.errors import ConfigurationError, format_actionable

# Template constants from docs/06 with the generated MVP project name.

PRODUCER_CONFIG_TEMPLATE = """\
# Generated by `kitefs init`.
#
# This configuration is for KiteFS feature store projects. It supports the full
# feature lifecycle that KiteFS provides: define, ingest, retrieve, materialize,
# and serve features.
#
# For projects that only need to consume an existing registry and online store,
# such as prediction services or REST APIs, use `kitefs init-config` to generate
# a lightweight configuration instead.
#
# runtime.target controls which configuration branch KiteFS uses:
#   local  = uses fixed conventional paths (see below)
#   remote = uses the settings in the `remote` section
#
# When runtime.target is "local", KiteFS uses these fixed paths relative to the
# project root:
#   Definitions:   ./feature_store/definitions/
#   Registry:      ./feature_store/registry.json
#   Offline store: ./feature_store/data/offline_store/
#   Online store:  ./feature_store/data/online_store/
#
# These paths are not configurable. They are created by `kitefs init` and used
# automatically when runtime.target is "local".

version: 1

project:
  # Project name. Generated as 'kitefs_featurestore_project'. You can change this manually.
  name: "kitefs_featurestore_project"

runtime:
  # Supported values: local, remote
  # Use "local" for local development and testing, "remote" for production.
  # Example:
  #   export KITEFS_RUNTIME_TARGET=remote
  target: "${KITEFS_RUNTIME_TARGET:-local}"

remote:
  # AWS region for S3 and DynamoDB access.
  # Used by all remote store backends.
  # Example:
  #   export KITEFS_AWS_REGION=eu-central-1
  region: "${KITEFS_AWS_REGION:-eu-central-1}"

  registry:
    type: aws_s3
    # S3 bucket for the published registry JSON file.
    # Example:
    #   export KITEFS_REMOTE_REGISTRY_S3_BUCKET=company-ml
    bucket: "${KITEFS_REMOTE_REGISTRY_S3_BUCKET:-}"
    # S3 object-key prefix for the registry.
    # The registry is stored at s3://{bucket}/{s3_prefix}/registry.json.
    # s3_prefix defaults to "kitefs".
    # Example:
    #   export KITEFS_REMOTE_REGISTRY_S3_PREFIX=kitefs
    s3_prefix: "${KITEFS_REMOTE_REGISTRY_S3_PREFIX:-kitefs}"

  offline_store:
    type: aws_s3
    # S3 bucket for remote offline Parquet files.
    # Example:
    #   export KITEFS_REMOTE_OFFLINE_S3_BUCKET=company-ml
    bucket: "${KITEFS_REMOTE_OFFLINE_S3_BUCKET:-}"
    # S3 object-key prefix for offline store data.
    # Offline data is stored under s3://{bucket}/{s3_prefix}/data/offline_store/.
    # s3_prefix defaults to "kitefs".
    # Example:
    #   export KITEFS_REMOTE_OFFLINE_S3_PREFIX=kitefs
    s3_prefix: "${KITEFS_REMOTE_OFFLINE_S3_PREFIX:-kitefs}"

  online_store:
    type: aws_dynamodb
    # Prefix for DynamoDB tables that store online feature values.
    # Each online-capable feature group gets a table named {dynamodb_table_prefix}{group_name}.
    # dynamodb_table_prefix defaults to "kitefs_".
    # Example:
    #   export KITEFS_REMOTE_ONLINE_DYNAMODB_TABLE_PREFIX=kitefs_
    dynamodb_table_prefix: "${KITEFS_REMOTE_ONLINE_DYNAMODB_TABLE_PREFIX:-kitefs_}"
"""

CONSUMER_CONFIG_TEMPLATE = """\
# Generated by `kitefs init-config`.
#
# This configuration is for projects that only need to consume an existing
# KiteFS registry and online store, such as REST APIs or prediction services.
#
# It does not include feature definitions, offline store, or local development
# scaffolding. For the full feature lifecycle (define, ingest, retrieve,
# materialize, serve), use `kitefs init` instead.
#
# runtime.target controls which configuration branch KiteFS uses:
#   local  = uses fixed conventional paths (see below)
#   remote = uses the settings in the `remote` section
#
# When runtime.target is "local", KiteFS uses these fixed paths relative to the
# project root:
#   Registry:    ./feature_store/registry.json
#   Online store: ./feature_store/data/online_store/
#
# These paths are not configurable. If you need the full feature lifecycle
# (definitions, offline store), run `kitefs init` instead.

version: 1

project:
  # Project name. Generated as 'kitefs_featurestore_project'. You can change this manually.
  name: "kitefs_featurestore_project"

runtime:
  # Supported values: local, remote
  # Use "local" for local development and testing, "remote" for production.
  # Example:
  #   export KITEFS_RUNTIME_TARGET=local
  target: "${KITEFS_RUNTIME_TARGET:-remote}"

remote:
  # AWS region for S3 and DynamoDB access.
  # Used by all remote store backends.
  # Example:
  #   export KITEFS_AWS_REGION=eu-central-1
  region: "${KITEFS_AWS_REGION:-eu-central-1}"

  registry:
    type: aws_s3
    # S3 bucket for the published registry JSON file.
    # Example:
    #   export KITEFS_REMOTE_REGISTRY_S3_BUCKET=company-ml
    bucket: "${KITEFS_REMOTE_REGISTRY_S3_BUCKET:-}"
    # S3 object-key prefix for the registry.
    # The registry is stored at s3://{bucket}/{s3_prefix}/registry.json.
    # s3_prefix defaults to "kitefs".
    # Example:
    #   export KITEFS_REMOTE_REGISTRY_S3_PREFIX=kitefs
    s3_prefix: "${KITEFS_REMOTE_REGISTRY_S3_PREFIX:-kitefs}"

  online_store:
    type: aws_dynamodb
    # Prefix for DynamoDB tables that store online feature values.
    # Each online-capable feature group gets a table named {dynamodb_table_prefix}{group_name}.
    # dynamodb_table_prefix defaults to "kitefs_".
    # Example:
    #   export KITEFS_REMOTE_ONLINE_DYNAMODB_TABLE_PREFIX=kitefs_
    dynamodb_table_prefix: "${KITEFS_REMOTE_ONLINE_DYNAMODB_TABLE_PREFIX:-kitefs_}"
"""

# Example definition from the Town Market reference use case.
EXAMPLE_DEFINITION = """\
# feature_store/definitions/town_market_features.py

from kitefs import FeatureGroup, Feature, EntityKey, EventTimestamp
from kitefs import FeatureType, StorageTarget, Expect
from kitefs import ValidationMode, Metadata

town_market_features = FeatureGroup(
    name="town_market_features",
    storage_target=StorageTarget.OFFLINE_AND_ONLINE,
    entity_key=EntityKey(
        name="town_id",
        dtype=FeatureType.INTEGER,
        description="Unique town identifier",
    ),
    event_timestamp=EventTimestamp(
        name="event_timestamp",
        description="When this value became available",
    ),
    features=[
        Feature(name="avg_price_per_sqm", dtype=FeatureType.FLOAT,
                description="Average sold price per sqm from sold listings in this town \
during the previous calendar month",
                expect=Expect().not_null().gt(0)),
    ],
    ingestion_validation=ValidationMode.ERROR,
    offline_retrieval_validation=ValidationMode.NONE,
    metadata=Metadata(
        description="Monthly town-level market aggregate",
        owner="data-science-team",
        tags={"domain": "real-estate", "cadence": "monthly"},
    ),
)
"""

EMPTY_REGISTRY: str = json.dumps({"feature_groups": {}}, sort_keys=True, indent=2, ensure_ascii=False) + "\n"

_GITIGNORE_ENTRIES = ("feature_store/data/", "feature_store/registry.json")


def _atomic_write_text(path: Path, content: str, created: list[Path]) -> None:
    """Write content to path atomically (temp-then-rename), append to created on success."""
    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=".tmp_", suffix="")
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as f:
            f.write(content)
        os.replace(tmp, path)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise
    created.append(path)


def _write_gitignore(path: Path, created: list[Path]) -> tuple[str, int]:
    """Manage .gitignore entries. Returns (action, n) where action is one of
    "created", "appended", or "untouched" and n is the number of entries added."""
    if not path.exists():
        _atomic_write_text(
            path,
            "".join(e + "\n" for e in _GITIGNORE_ENTRIES),
            created,
        )
        return "created", len(_GITIGNORE_ENTRIES)

    existing = path.read_text(encoding="utf-8")
    existing_lines = {line.rstrip() for line in existing.splitlines()}
    missing = [e for e in _GITIGNORE_ENTRIES if e not in existing_lines]

    if not missing:
        return "untouched", 0

    # Preserve original bytes; prepend a newline only if the file doesn't already
    # end with one so the appended entries land on their own lines.
    suffix = "".join(e + "\n" for e in missing)
    if existing and not existing.endswith("\n"):
        suffix = "\n" + suffix
    with path.open("a", encoding="utf-8") as f:
        f.write(suffix)
    return "appended", len(missing)


def _gitignore_summary_line(action: str, n: int) -> str | None:
    if action == "created":
        return "  .gitignore"
    if action == "appended":
        word = "entry" if n == 1 else "entries"
        return f"  .gitignore (appended {n} {word})"
    return None


def _rollback_producer(
    created: list[Path],
    created_dirs: list[Path],
    gitignore_path: Path,
    gitignore_snapshot: str | None,
) -> None:
    """Best-effort rollback after a failed init_producer attempt.

    Unlinks files created by the attempt, restores a pre-existing .gitignore
    that was modified, and removes any empty scaffold directories.
    """
    for p in reversed(created):
        p.unlink(missing_ok=True)
    if gitignore_snapshot is not None and gitignore_path.exists():
        with contextlib.suppress(OSError):
            gitignore_path.write_text(gitignore_snapshot, encoding="utf-8")
    for d in reversed(created_dirs):
        with contextlib.suppress(OSError):
            d.rmdir()


# ---------------------------------------------------------------------------
# Public scaffold functions
# ---------------------------------------------------------------------------


def init_producer(root: Path) -> str:
    """Create the full producer scaffold under root. Returns the stdout summary.

    Raises ConfigurationError when kitefs.yaml already exists or when
    registry.json / town_market_features.py already exist.
    On any failure partway through, removes only the files this call created.
    """
    config_path = root / "kitefs.yaml"
    registry_path = root / "feature_store" / "registry.json"
    definition_path = root / "feature_store" / "definitions" / "town_market_features.py"
    gitignore_path = root / ".gitignore"

    if config_path.exists():
        raise ConfigurationError(
            f"kitefs.yaml already exists at {config_path.resolve()}; "
            "remove it or run `kitefs init` from a different directory."
        )
    for conflict in (registry_path, definition_path):
        if conflict.exists():
            raise ConfigurationError(
                f"{conflict.resolve()} already exists; remove it or run `kitefs init` from a different directory."
            )

    # Determine which scaffold directories do not yet exist so rollback can remove them.
    _scaffold_dirs = [
        root / "feature_store",
        root / "feature_store" / "definitions",
        root / "feature_store" / "data",
        root / "feature_store" / "data" / "offline_store",
        root / "feature_store" / "data" / "online_store",
    ]
    created_dirs = [d for d in _scaffold_dirs if not d.exists()]

    # Snapshot a pre-existing .gitignore so an appended entry can be rolled back.
    gitignore_snapshot: str | None = gitignore_path.read_text(encoding="utf-8") if gitignore_path.exists() else None

    created: list[Path] = []
    try:
        for d in _scaffold_dirs:
            d.mkdir(parents=True, exist_ok=True)

        _atomic_write_text(definition_path, EXAMPLE_DEFINITION, created)
        _atomic_write_text(registry_path, EMPTY_REGISTRY, created)
        gi_action, gi_n = _write_gitignore(gitignore_path, created)
        _atomic_write_text(config_path, PRODUCER_CONFIG_TEMPLATE, created)  # last — commit marker
    except OSError as exc:
        _rollback_producer(created, created_dirs, gitignore_path, gitignore_snapshot)
        raise ConfigurationError(
            format_actionable(
                setting=str(root.resolve()),
                problem=f"could not create KiteFS scaffold: {exc}",
                next_step="check permissions and disk space, then rerun 'kitefs init'",
            )
        ) from exc
    except BaseException:
        _rollback_producer(created, created_dirs, gitignore_path, gitignore_snapshot)
        raise

    lines = [
        f"Created KiteFS producer scaffold in {root.resolve()}:",
        "  kitefs.yaml",
        "  feature_store/definitions/town_market_features.py",
        "  feature_store/registry.json",
        "  feature_store/data/offline_store/",
        "  feature_store/data/online_store/",
    ]
    gi_line = _gitignore_summary_line(gi_action, gi_n)
    if gi_line is not None:
        lines.append(gi_line)
    lines.append("")
    lines.append("Next step: edit feature_store/definitions/, then run 'kitefs apply' to register them.")
    return "\n".join(lines)


def init_config(root: Path) -> str:
    """Create a consumer-only kitefs.yaml under root. Returns the stdout summary.

    Raises ConfigurationError when kitefs.yaml already exists.
    """
    config_path = root / "kitefs.yaml"

    if config_path.exists():
        raise ConfigurationError(
            f"kitefs.yaml already exists at {config_path.resolve()}; "
            "remove it or run `kitefs init-config` from a different directory."
        )

    created: list[Path] = []
    try:
        _atomic_write_text(config_path, CONSUMER_CONFIG_TEMPLATE, created)
    except OSError as exc:
        for p in reversed(created):
            p.unlink(missing_ok=True)
        raise ConfigurationError(
            format_actionable(
                setting=str(root.resolve()),
                problem=f"could not create consumer configuration: {exc}",
                next_step="check permissions and disk space, then rerun 'kitefs init-config'",
            )
        ) from exc
    except BaseException:
        for p in reversed(created):
            p.unlink(missing_ok=True)
        raise

    return (
        f"Created KiteFS consumer config in {root.resolve()}:\n"
        "  kitefs.yaml\n"
        "\n"
        "Next step: edit the remote bucket and dynamodb_table_prefix placeholders "
        "in kitefs.yaml before running 'kitefs list', 'kitefs describe', or get_online_features()."
    )
